# Generated by Django 3.0.8 on 2020-07-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('status', '0001_initial'),
        ('organization', '0001_initial'),
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Title')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
