# Generated by Django 3.1 on 2020-08-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('organization', '__first__'),
        ('status', '0001_initial'),
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.title')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
