# Generated by Django 3.0.8 on 2020-07-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('title', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.Title'),
        ),
    ]
