# Generated by Django 3.0.8 on 2020-08-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('staff', '0002_staff_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='role.Role'),
            preserve_default=False,
        ),
    ]
