# Generated by Django 3.1 on 2020-08-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizationtype', '0002_auto_20200817_1206'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=11, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('IsSaturdayWorkDay', models.BooleanField(default=True)),
                ('IsSundayWorkDay', models.BooleanField(default=True)),
                ('CanApproveRight', models.BooleanField(default=True)),
                ('OrganizationType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizationtype.organizationtype')),
                ('Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='status.status')),
                ('UpperOrganization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
    ]
