# Generated by Django 3.0.8 on 2020-07-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizationtype', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('OrganizationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationtype.OrganizationType')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status')),
                ('UpperOrganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'db_table': 'Organization',
            },
        ),
    ]
