# Generated by Django 3.0.8 on 2020-07-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('organization', '0001_initial'),
        ('organizationtype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='OrganizationType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationtype.OrganizationType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status'),
        ),
        migrations.AddField(
            model_name='organization',
            name='UpperOrganization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
