# Generated by Django 3.1 on 2020-08-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_auto_20200817_1206'),
        ('organization', '0002_auto_20200817_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ManagerTitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='title.title'),
        ),
        migrations.AddField(
            model_name='organization',
            name='WorkEndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='WorkStartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
