# Generated by Django 3.0.8 on 2020-08-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20200806_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='CanApproveRight',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='IsSaturdayWorkDay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='IsSundayWorkDay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='Telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
