# Generated by Django 3.0.8 on 2020-08-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
        ('organization', '0003_auto_20200820_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.Shift'),
        ),
    ]
