# Generated by Django 3.0.8 on 2020-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='CanApproveRight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='IsSaturdayWorkDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='IsSundayWorkDay',
            field=models.BooleanField(default=False),
        ),
    ]
