# Generated by Django 3.0.8 on 2020-08-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='Shift',
        ),
    ]
