# Generated by Django 3.0.8 on 2020-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20200826_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
