# Generated by Django 3.0.8 on 2020-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20200828_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
