# Generated by Django 3.1 on 2020-08-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('rightstatus', '0001_initial'),
        ('righttype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EndDate', models.DateField(auto_now_add=True, max_length=50, null=True)),
                ('DateOfReturn', models.DateField(auto_now_add=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('Approver1', models.IntegerField(blank=True, null=True)),
                ('Approver2', models.IntegerField(blank=True, null=True)),
                ('RightNumber', models.IntegerField(blank=True, null=True)),
                ('DenyExplanation', models.CharField(blank=True, max_length=50)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('RightStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rightstatus.rightstatus')),
                ('RightType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='righttype.righttype')),
            ],
            options={
                'db_table': 'Right',
            },
        ),
    ]
