# Generated by Django 3.0.8 on 2020-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='Approver2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
