# Generated by Django 3.0.8 on 2020-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0003_auto_20200819_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='Approver2',
        ),
        migrations.AddField(
            model_name='right',
            name='StartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
