# Generated by Django 3.0.8 on 2020-08-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('righttype', '0002_auto_20200817_1206'),
        ('right', '0004_auto_20200819_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='RightType',
        ),
        migrations.AddField(
            model_name='right',
            name='RightMainTypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='righttype.RightType'),
        ),
    ]
