# Generated by Django 3.0.8 on 2020-08-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0005_auto_20200819_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='right',
            old_name='RightMainTypes',
            new_name='RightType',
        ),
    ]
