# Generated by Django 3.0.8 on 2020-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0006_auto_20200819_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='IKHasField',
            field=models.BooleanField(default=False),
        ),
    ]
