# Generated by Django 3.0.8 on 2020-08-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0008_auto_20200825_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='Address',
        ),
        migrations.AddField(
            model_name='right',
            name='KvkkIsChecked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
