# Generated by Django 3.0.8 on 2020-08-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0010_auto_20200826_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='RightPicture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
