# Generated by Django 3.0.8 on 2020-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('right', '0011_auto_20200826_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='RightNumber',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
