# Generated by Django 3.0.8 on 2020-09-11 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('right', '0011_right_rightpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='CreatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RightCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='right',
            name='CreatedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='right',
            name='ModifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RightModifiedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='right',
            name='ModifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
