# Generated by Django 3.0.8 on 2020-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('righthistory', '0002_auto_20200817_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='righthistory',
            name='ChangedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
