# Generated by Django 3.0.8 on 2020-08-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrole',
            table='UserRole',
        ),
    ]
