# Generated by Django 3.0.8 on 2020-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='IsHierarchical',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
