# Generated by Django 3.1 on 2020-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personeducation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeducation',
            name='GraduationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personeducation',
            name='StartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
