# Generated by Django 3.0.8 on 2020-08-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personeducation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personeducation',
            old_name='CityId',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='personeducation',
            old_name='PersonId',
            new_name='Person',
        ),
    ]
