# Generated by Django 3.1 on 2020-08-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lable', models.CharField(blank=True, max_length=100, null=True)),
                ('Icon', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('Root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='navigationbar.navigationbar')),
            ],
            options={
                'db_table': 'NavigationBar',
            },
        ),
    ]
