# Generated by Django 3.1 on 2020-08-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigationbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbar',
            name='Root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigationbar.navigationbar'),
        ),
    ]
