# Generated by Django 3.1 on 2020-08-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigationbar', '0002_auto_20200819_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationbar',
            old_name='Icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='navigationbar',
            old_name='Lable',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='navigationbar',
            old_name='Root',
            new_name='root',
        ),
        migrations.RenameField(
            model_name='navigationbar',
            old_name='To',
            new_name='to',
        ),
    ]
