# Generated by Django 3.0.8 on 2020-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocationdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocationdays',
            name='DayType',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
