# Generated by Django 3.0.8 on 2020-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocationdays', '0002_vocationdays_daytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationdays',
            name='DayType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
