# Generated by Django 3.0.8 on 2020-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocationdays', '0004_auto_20200820_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationdays',
            name='DateDay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
