# Generated by Django 3.0.8 on 2020-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocationdays', '0005_auto_20200821_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationdays',
            name='DayType',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
