# Generated by Django 3.0.8 on 2020-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('FirstShiftStartTime', models.TimeField()),
                ('FirstShiftEndTime', models.TimeField()),
                ('SecondShiftStartTime', models.TimeField()),
                ('SecondShiftEndTime', models.TimeField()),
                ('TotalHours', models.IntegerField(blank=True, null=True)),
                ('IsSaturDayHalfDay', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shift',
            },
        ),
    ]
