# Generated by Django 3.0.8 on 2020-08-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='FirstShiftEndTime',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='FirstShiftStartTime',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='IsSaturDayHalfDay',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='SecondShiftEndTime',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='SecondShiftStartTime',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='TotalHours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
