# Generated by Django 3.0.8 on 2020-08-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personelinformation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personelinformation',
            name='Person',
        ),
    ]
