# Generated by Django 3.0.8 on 2020-08-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_remove_person_personelinformation'),
        ('personelinformation', '0002_remove_personelinformation_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelinformation',
            name='Person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Person', to='person.Person'),
            preserve_default=False,
        ),
    ]
