# Generated by Django 3.0.8 on 2020-09-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_auto_20200817_1206'),
        ('personemployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemployment',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personemployment',
            name='StartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personemployment',
            name='Title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='title.Title'),
        ),
    ]
