# Generated by Django 3.0.8 on 2020-08-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
    ]
