# Generated by Django 3.0.8 on 2020-09-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightleave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightleave',
            name='Earning',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
    ]
