# Generated by Django 3.0.8 on 2020-08-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gender', '0001_initial'),
        ('district', '0001_initial'),
        ('person', '0007_auto_20200813_1010'),
        ('city', '0001_initial'),
        ('maritalstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('FatherName', models.CharField(blank=True, max_length=100, null=True)),
                ('MotherName', models.CharField(blank=True, max_length=100, null=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('BloodType', models.CharField(blank=True, max_length=50, null=True)),
                ('MilitaryStatus', models.IntegerField(blank=True, null=True)),
                ('MilitaryDischargeData', models.DateField(blank=True, null=True)),
                ('PreviousLastname', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gender.Gender')),
                ('MaritalStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maritalstatus.MaritalStatus')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('PlaceOfBirthCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthCityId', to='city.City')),
                ('PlaceOfBirthDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthDistrictId', to='district.District')),
                ('RegisteredCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredCityId', to='city.City')),
                ('RegisteredDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredDistrictId', to='district.District')),
            ],
            options={
                'db_table': 'PersonIdentity',
            },
        ),
    ]
