# Generated by Django 3.1 on 2020-08-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('city', '0001_initial'),
        ('gender', '0001_initial'),
        ('district', '0001_initial'),
        ('maritalstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('FatherName', models.CharField(blank=True, max_length=100, null=True)),
                ('MotherName', models.CharField(blank=True, max_length=100, null=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('BloodType', models.CharField(blank=True, max_length=50, null=True)),
                ('MilitaryStatus', models.IntegerField(blank=True, null=True)),
                ('MilitaryDischargeData', models.DateField(blank=True, null=True)),
                ('PreviousLastname', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gender.gender')),
                ('MaritalStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maritalstatus.maritalstatus')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('PlaceOfBirthCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthCity', to='city.city')),
                ('PlaceOfBirthDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthDistrict', to='district.district')),
                ('RegisteredCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredCity', to='city.city')),
                ('RegisteredDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredDistrict', to='district.district')),
            ],
            options={
                'db_table': 'PersonIdentity',
            },
        ),
    ]
