# Generated by Django 3.1 on 2020-08-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200817_1206'),
        ('district', '0002_auto_20200817_1206'),
        ('personidentity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personidentity',
            name='PlaceOfBirthCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthCity', to='city.city'),
        ),
        migrations.AlterField(
            model_name='personidentity',
            name='PlaceOfBirthDistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthDistrict', to='district.district'),
        ),
        migrations.AlterField(
            model_name='personidentity',
            name='RegisteredCity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredCity', to='city.city'),
        ),
        migrations.AlterField(
            model_name='personidentity',
            name='RegisteredDistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredDistrict', to='district.district'),
        ),
    ]
