# Generated by Django 3.0.8 on 2020-08-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('city', '0001_initial'),
        ('personidentity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personidentity',
            name='PlaceOfBirthCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthCity', to='city.City'),
        ),
        migrations.AlterField(
            model_name='personidentity',
            name='PlaceOfBirthDistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfBirthDistrict', to='district.District'),
        ),
        migrations.AlterField(
            model_name='personidentity',
            name='RegisteredCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredCity', to='city.City'),
        ),
        migrations.AlterField(
            model_name='personidentity',
            name='RegisteredDistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredDistrict', to='district.District'),
        ),
    ]
