# Generated by Django 3.0.8 on 2020-08-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0008_auto_20200813_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractType', models.IntegerField(blank=True, null=True)),
                ('JobStartDate', models.DateField(blank=True, null=True)),
                ('Degree', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('JobCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'db_table': 'PersonBusiness',
            },
        ),
    ]
