# Generated by Django 3.1 on 2020-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personbusiness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbusiness',
            name='FirstBudger',
        ),
        migrations.AddField(
            model_name='personbusiness',
            name='FirstBudget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
