# Generated by Django 3.1 on 2020-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personbusiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbusiness',
            name='JobStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personbusiness',
            name='SGKEnterDate',
            field=models.DateTimeField(auto_now_add=True, max_length=50, null=True),
        ),
    ]
