# Generated by Django 3.0.8 on 2020-08-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personbusiness', '0003_personbusiness_leavedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbusiness',
            name='FormerSeniority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
