# Generated by Django 3.0.8 on 2020-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personbusiness', '0004_personbusiness_formerseniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbusiness',
            name='JobStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
