# Generated by Django 3.0.8 on 2020-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personbusiness', '0005_auto_20200907_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbusiness',
            name='JobStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
