# Generated by Django 3.1.1 on 2020-09-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_auto_20200817_1206'),
        ('organization', '0006_auto_20200828_0941'),
        ('personbusiness', '0006_auto_20200907_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbusiness',
            name='PayrollOrganization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='personbusiness',
            name='PayrollStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personbusiness',
            name='PayrollTittle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='title.title'),
        ),
    ]
