# Generated by Django 3.0.8 on 2020-09-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personbusiness', '0007_auto_20200908_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbusiness',
            name='PayrollOrganization',
        ),
        migrations.RemoveField(
            model_name='personbusiness',
            name='PayrollStartDate',
        ),
        migrations.RemoveField(
            model_name='personbusiness',
            name='PayrollTittle',
        ),
    ]
