# Generated by Django 3.0.8 on 2020-08-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('righttype', '0002_auto_20200817_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='righttype',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
