# Generated by Django 3.0.8 on 2020-08-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('righttype', '0004_auto_20200820_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='righttype',
            name='MaxDayOff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
