# Generated by Django 3.0.8 on 2020-07-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffID', models.IntegerField(blank=True, null=True)),
                ('EntryDate', models.DateField(auto_now_add=True, max_length=50, null=True)),
                ('TerminationDate', models.DateField(auto_now_add=True, max_length=50, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'db_table': 'PersonHistory',
            },
        ),
    ]
