# Generated by Django 3.1 on 2020-08-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('personhistory', '0002_personhistory_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personhistory',
            name='Staff',
        ),
        migrations.AddField(
            model_name='personhistory',
            name='StafId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StafId', to='staff.staff'),
            preserve_default=False,
        ),
    ]
