# Generated by Django 3.1 on 2020-08-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('personhistory', '0003_auto_20200814_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personhistory',
            name='StafId',
        ),
        migrations.AddField(
            model_name='personhistory',
            name='Staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
