# Generated by Django 3.0.8 on 2020-07-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gender', '0001_initial'),
        ('city', '0001_initial'),
        ('maritalstatus', '0001_initial'),
        ('nationality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Surname', models.CharField(blank=True, max_length=50, null=True)),
                ('IdentityID', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('BirthDate', models.DateField(blank=True, max_length=50, null=True)),
                ('State', models.IntegerField(blank=True, null=True)),
                ('IdentitySerialNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('IdentityVolumeNo', models.CharField(blank=True, max_length=50, null=True)),
                ('MothersName', models.CharField(blank=True, max_length=50, null=True)),
                ('FathersName', models.CharField(blank=True, max_length=50, null=True)),
                ('BloodType', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Picture', models.BinaryField(max_length=16777215)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.Gender')),
                ('MaritalStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maritalstatus.MaritalStatus')),
                ('Nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationality.Nationality')),
                ('PlaceOfRegistryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfRegistryID', to='city.City')),
                ('RegisteredProvinceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisteredProvinceID', to='city.City')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
