# Generated by Django 3.1 on 2020-08-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('nationality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Surname', models.CharField(blank=True, max_length=50, null=True)),
                ('IdentityID', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.IntegerField(blank=True, null=True)),
                ('IdentitySerialNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('IdentityVolumeNo', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Picture', models.BinaryField(blank=True, max_length=16777215, null=True)),
                ('Nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NationalityId', to='nationality.nationality')),
                ('PlaceOfRegistryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfRegistryID', to='city.city')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
