# Generated by Django 3.0.8 on 2020-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Picture',
            field=models.BinaryField(blank=True, max_length=16777215, null=True),
        ),
    ]
