# Generated by Django 3.1 on 2020-08-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200817_1206'),
        ('nationality', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NationalityId', to='nationality.nationality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='PlaceOfRegistryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlaceOfRegistryID', to='city.city'),
        ),
    ]
