# Generated by Django 3.1 on 2020-08-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200817_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='IdentitySerialNumber',
        ),
        migrations.RemoveField(
            model_name='person',
            name='IdentityVolumeNo',
        ),
    ]
