# Generated by Django 3.0.8 on 2020-08-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
        ('person', '0002_auto_20200804_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gender', to='gender.Gender'),
        ),
    ]
