# Generated by Django 3.0.8 on 2020-08-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personelinformation', '0002_remove_personelinformation_person'),
        ('person', '0003_auto_20200804_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='PersonelInformation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PersonelInformation', to='personelinformation.PersonelInformation'),
            preserve_default=False,
        ),
    ]
