# Generated by Django 3.1 on 2020-08-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200818_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='PlaceOfRegistryID',
        ),
    ]
