# Generated by Django 3.0.8 on 2020-08-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_personelinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='PersonelInformation',
        ),
    ]
