# Generated by Django 3.1 on 2020-08-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_person_placeofregistryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
