# Generated by Django 3.0.8 on 2020-08-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
        ('person', '0005_remove_person_personelinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.Gender'),
        ),
    ]
