# Generated by Django 3.0.8 on 2020-08-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20200810_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='BirthDate',
        ),
        migrations.RemoveField(
            model_name='person',
            name='BloodType',
        ),
        migrations.RemoveField(
            model_name='person',
            name='FathersName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='MaritalStatusID',
        ),
        migrations.RemoveField(
            model_name='person',
            name='MothersName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='RegisteredProvinceID',
        ),
    ]
