# Generated by Django 3.0.8 on 2020-08-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20200826_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
