# Generated by Django 3.1 on 2020-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200817_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='PlateCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
