# Generated by Django 3.1 on 2020-08-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status')),
            ],
            options={
                'db_table': 'District',
            },
        ),
    ]
