# Generated by Django 3.1 on 2020-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_auto_20200817_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='Code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
