# Generated by Django 3.1 on 2020-08-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Surname', models.CharField(blank=True, max_length=100, null=True)),
                ('IdentityNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Birtyday', models.DateField(blank=True, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('Relation', models.IntegerField(blank=True, null=True)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
            options={
                'db_table': 'PersonFamily',
            },
        ),
    ]
