# Generated by Django 3.0.8 on 2020-08-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0008_auto_20200813_1019'),
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Surname', models.CharField(blank=True, max_length=100, null=True)),
                ('IdentityNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Birtyday', models.DateField(blank=True, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('Relation', models.IntegerField(blank=True, null=True)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.Gender')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
            options={
                'db_table': 'PersonFamily',
            },
        ),
    ]
