# Generated by Django 3.0.8 on 2020-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
